pool: MLdreamdecor 
trigger: none
stages:
- stage: 
  jobs:
  - job: 
    displayName: terraforminit
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/main'
        backendServiceArm: 'mlddsc'
        backendAzureRmResourceGroupName: 'temp'
        backendAzureRmStorageAccountName: 'mytempstorage090'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/main'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/main'
        environmentServiceNameAzureRM: 'mlddsc'
    


