pool: MLdreamdecor 
trigger:
- feature/*
- main

stages: 
- stage: RgEnvironment
  displayName: RG Environment

  jobs:

  - job: TerraformInitPlan
    displayName: Terraform Init & Plan
    steps:
    - task: TerraformTask@5
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'mlddsc'
        backendAzureRmResourceGroupName: 'temp'
        backendAzureRmStorageAccountName: 'mytempstorage090'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'tfstate'

    - task: TerraformTask@5
      displayName: Terraform validate
      inputs:
        provider: 'azurerm'
        command: 'validate'

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'mlddsc'


  - job: Manualvalidation
    displayName: Manual Validation
    dependsOn: TerraformInitPlan
    pool: server
    steps:
    - task: ManualValidation@1
      displayName: Approve Deployment
      inputs:
        instructions: 'Please approve'
        onTimeout: 'reject'
        timeoutInMinutes: '1440'


  - job: TerraformApply
    displayName: Terraform Apply
    dependsOn: Manualvalidation
    condition: succeeded('Manualvalidation')   # Corrected
    steps:
    - task: TerraformTask@5
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'mlddsc'
        backendAzureRmResourceGroupName: 'temp'
        backendAzureRmStorageAccountName: 'mytempstorage090'
        backendAzureRmContainerName: 'mycontainer'
        backendAzureRmKey: 'tfstate'

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'mlddsc'
